version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-server
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /mnt/efs:/var/jenkins_home
